### ISSUE TITLE
Version 0.3.0 Roadmap (Meta-Ticket)

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/airship#27]
The final beta looks like this:

- [x] #22 - Password Reset Feature
- [x] #25 - Gearify the Cabin Classes
- [x] #23 - Make Comments Compatible with Static Pages
- [x] #24 - Web Interface for Managing Packages
- [x] #30 - Two-Factor Authentication
- [x] #35 - Progressive Login Attempt Rate-Limiting
- [x] #34 - Optional HPKP Headers

Afterwards, I'll spend a bunch of time on boyscouting.
